# Publish all joint states ------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Velocity Controllers ----------------------------------
  joint_back_left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_back_right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

#Steering Controllers ----------------------------------
  joint_front_left_axle_steering_controller:
    type: position_controllers/JointPositionController
    joint: joint_front_left_axle
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_right_axle_steering_controller:
    type:  position_controllers/JointPositionController
    joint: joint_front_right_axle
    pid: {p: 100.0, i: 0.01, d: 10.0}

